//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokyoFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int MaChiTietDH { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuongSP { get; set; }
        public Nullable<int> MaKT { get; set; }
        public Nullable<double> GiaBan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
