//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokyoFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.PhanHois = new HashSet<PhanHoi>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public string TenSP { get; set; }
        public string TenThuongHieu { get; set; }
        public Nullable<int> MaMau { get; set; }
        public string Anh { get; set; }
        public Nullable<double> GiaGoc { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
        public virtual MauSac MauSac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
    }
}
